package namegen

var (
	germanFirstNames = []string{
		// female first names
		"Alexandra", "Alexandrea", "Algelika", "Alina", "Amelie", "Andrea", "Angelina", "Anita", "Anja", "Anna", "Anna-Lena", "Annika", "Astrid",
		"Barbara", "Bettina", "Berta", "Bianca", "Birgit", "Brigitte",
		"Carina", "Caroline", "Celina", "Chiara", "Christina", "Christine", "Clara", "Claudia", "Cornelia",
		"Daniela", "Denise", "Doris",
		"Elena", "Elisa", "Elisabeth", "Ella", "Emely", "Emilia", "Emily", "Emma", "Eva", "Eva-Maria",
		"Fiona", "Franziska",
		"Hanna", "Hannah", "Helena",
		"Ines", "Iris", "Isabel", "Isabella",
		"Jacqueline", "Jacquline", "Jana", "Janine", "Jasmin", "Jennifer", "Jessica", "Johanna", "Julia",
		"Karin", "Katharina", "Katrin", "Kerstin", "Konstanze",
		"Lara", "Larissa", "Laura", "Lea", "Lena", "Leonie", "Lilly", "Lina", "Lisa", "Livia", "Luisa",
		"Magdalena", "Maja", "Manuela", "Maria", "Marie", "Marion", "Marlene", "Martina", "Melanie", "Melina", "Mia", "Michaela", "Michelle", "Miriam", "Mona", "Monika",
		"Nadine", "Natalie", "Nicole", "Nina", "Nora",
		"Patricia", "Paula", "Petra", "Pia",
		"Rebecca", "Rosa",
		"Sabine", "Sabrina", "Sandra", "Sarah", "Selina", "Silvia", "Simone", "Sonja", "Sophia", "Sophie", "Stefanie", "Susanne",
		"Tamara", "Tanja", "Theresa",
		"Valentina", "Valerie", "Vanessa", "Verena", "Viktoria",
		"Yvonne",
		"Zafira",

		// male firstnames
		"Adrian", "Alexander", "Andreas", "Anton",
		"Ben", "Benedikt", "Benjamin", "Bernd", "Bernhard",
		"Christian", "Christoph", "Christopher", "Clemens",
		"Daniel", "David", "Dirk", "Dominik",
		"Elias", "Emanuel", "Emil", "Erik",
		"Fabian", "Fabio", "Felix", "Finn", "Florian", "Frank", "Franz",
		"Gabriel", "Georg", "Gerald", "Gerhard", "Gernot", "Gregor", "Günther",
		"Hannes", "Harald", "Helmut", "Herbert",
		"Jakob", "Jan", "Jens", "Johann", "Johannes", "Jonas", "Jonathan", "Josef", "Joseph", "Julian", "Justin", "Jürgen",
		"Karl", "Kevin", "Kilian", "Klaus", "Konstantin", "Kurt",
		"Leo", "Leon", "Lorenz", "Luca", "Luis", "Lukas",
		"Manfred", "Manuel", "Marc", "Marcel", "Marco", "Mario", "Markus", "Martin", "Marvin", "Matteo", "Matthias", "Max", "Maximilian", "Michael", "Moritz",
		"Nico", "Nicolas", "Niklas", "Noah",
		"Oliver", "Oskar", "Oswald",
		"Pascal", "Patrick", "Patrik", "Paul", "Peter", "Philipp",
		"Ralph", "Raphael", "Reinhard", "René", "Richard", "Robert", "Roland", "Roman",
		"Samuel", "Sandro", "Sascha", "Sebastian", "Simon", "Stefan",
		"Theo", "Theodor", "Thomas", "Tim", "Tobias",
		"Valentin", "Vincent",
		"Werner", "Wolfgang",


	}

	germanLastNames = []string{
		"Abraham", "Achleitner", "Adam", "Aichinger", "Aigner", "Albrecht", "Altmann", "Amann", "Amon", "Angerer", "Arnold", "Artner", "Aschauer", "Auer", "Augustin", "Auinger",
		"Bacher", "Bachler", "Bachmann", "Bader", "Baier", "Barth", "Bartl", "Bauer", "Baumann", "Baumgartner", "Bayer", "Beck", "Beer", "Berger", "Bergmann", "Bernhard", "Bichler", "Binder", "Bischof", "Bock", "Bogner", "Brandl", "Brandner", "Brandstetter", "Brandstätter", "Braun", "Brenner", "Bruckner", "Brugger", "Brunner", "Buchberger", "Buchegger", "Bucher", "Buchinger", "Buchner", "Burger", "Burgstaller", "Burtscher", "Böck", "Böhm", "Bösch",
		"Danner", "Denk", "Dengg", "Deutsch", "Dietrich", "Dobler", "Doppler", "Dorner", "Draxler",
		"Eberharter", "Eberl", "Ebner", "Ecker", "Eder", "Edlinger", "Egger", "Eibl", "Eichberger", "Eichinger", "Eigner", "Erhart", "Ernst", "Ertl",
		"Falkner", "Fasching", "Feichtinger", "Fellner", "Feistritzer", "Fiala", "Fichtinger", "Fiedler", "Fink", "Fischer", "Fleischhacker", "Forster", "Forstner", "Frank", "Franz", "Friedl", "Friedrich", "Fritsch", "Fritz", "Fröhlich", "Frühwirth", "Fuchs", "Führer", "Fürst",
		"Gabriel", "Gangl", "Gartner", "Gasser", "Gassner", "Gatternig", "Geiger", "Geisler", "Geyer", "Glaser", "Glatz", "Gmeiner", "Grabner", "Graf", "Gratzer", "Greiner", "Grill", "Gritsch", "Gross", "Groß", "Gruber", "Grünwald", "Gschwandtner", "Gutmann",
		"Haas", "Haberl", "Hackl", "Hafner", "Hagen", "Hager", "Hahn", "Haider", "Haidinger", "Haller", "Hammer", "Hammerl", "Handl", "Handler", "Harrer", "Hartl", "Hartmann", "Haslinger", "Hauer", "Hauser", "Heindl", "Heinrich", "Hemetsberger", "Herbst", "Hermann", "Herzog", "Hinterberger", "Hinteregger", "Hinterleitner", "Hirsch", "Hochreiter", "Hofbauer", "Hofer", "Hoffmann", "Hofmann", "Hofstätter", "Holzer", "Holzinger", "Holzmann", "Horvath", "Huber", "Huemer", "Hufnagl", "Humer", "Hummer", "Hutter", "Hämmerle", "Hödl", "Höfler", "Höller", "Hölzl", "Hörmann", "Hütter",
		"Jahn", "Jandl", "Janisch", "Jovanovic", "Jung", "Jungwirth", "Jäger",
		"Kainz", "Kaiser", "Kaltenbrunner", "Kapeller", "Kargl", "Karl", "Karner", "Kastner", "Kaufmann", "Kellner", "Kern", "Kerschbaumer", "Kickl", "Kienzl", "Kirchmair", "Kirchner", "Klammer", "Klein", "Klinger", "Klug", "Knapp", "Knoll", "Koch", "Kofler", "Kogler", "Kohl", "Koller", "Kollmann", "Konrad", "Kopp", "Kovacs", "Kraft", "Krainer", "Kramer", "Krammer", "Kraus", "Kremser", "Krenn", "Kreuzer", "Kronberger", "Kröll", "Kugler", "Kummer", "Kurz", "Köberl", "Köck", "Köhler", "König",
		"Lackner", "Lamprecht", "Lang", "Langer", "Lappi", "Lechner", "Lederer", "Leeb", "Lehner", "Leitgeb", "Leitner", "Lengauer", "Lenz", "Lettner", "Lindner", "List", "Loidl", "Lorenz", "Ludwig", "Luger", "Lukas", "Lutz", "Löffler",
		"Mader", "Mandl", "Maier", "Maierhofer", "Mair", "Mairhofer", "Mandl", "Markovic", "Martin", "Maurer", "Mayer", "Mayerhofer", "Mayr", "Mayrhofer", "Meier", "Meixner", "Messner", "Meyer", "Mitterer", "Moosbrugger", "Moser", "Muhr", "Mühlbacher", "Müller", "Müllner",
		"Nagl", "Nemeth", "Neubauer", "Neuhauser", "Neuhold", "Neumann", "Neumayer", "Neuner", "Neuwirth", "Nikolic", "Novak", "Nowak", "Nussbaumer", "Nußbaumer",
		"Ofner", "Ölschützer", "Ortner", "Oswald", "Ott", "Otti", "Ozwirk",
		"Paar", "Pacher", "Pammer", "Pariasek", "Paul", "Payer", "Peer", "Penz", "Peter", "Petrovic", "Petz", "Pfeffer", "Pfeifer", "Pfeiffer", "Pfister", "Pfleger", "Pichler", "Pilz", "Pinter", "Pirker", "Plank", "Plattner", "Platzer", "Pointner", "Pokorny", "Pollak", "Posch", "Prem", "Prinz", "Probst", "Pucher", "Putz", "Pöll", "Pölzl", "Pöschl", "Pühringer",
		"Raab", "Rabensteiner", "Rabl", "Ranninger", "Rainer", "Rath", "Rauch", "Rausch", "Rauscher", "Rauter", "Rechberger", "Redl", "Reich", "Reichl", "Reindl", "Reiner", "Reinisch", "Reischl", "Reisinger", "Reiter", "Reiterer", "Renner", "Resch", "Richter", "Rieder", "Riedl", "Riedler", "Rieger", "Riegler", "Rieser", "Ritter", "Rosenberger", "Roth", "Rupp",
		"Sailer", "Sattler", "Sauer", "Schabus", "Schachinger", "Schachner", "Schaffer", "Schaller", "Scharf", "Schatz", "Schauer", "Scheiber", "Schenk", "Scheucher", "Schiefer", "Schiller", "Schindler", "Schlager", "Schlögl", "Schmid", "Schmidt", "Schmied", "Schnabl", "Schneeberger", "Schneider", "Schober", "Scholz", "Schranz", "Schreiber", "Schreiner", "Schubert", "Schuh", "Schuller", "Schulz", "Schuster", "Schwab", "Schwaiger", "Schwaighofer", "Schwarz", "Schweiger", "Schweighofer", "Schön", "Schöpf", "Schütz", "Seebacher", "Seidl", "Siegl", "Simon", "Singer", "Sommer", "Sonnleitner", "Spitzer", "Springer", "Stadler", "Stangl", "Stark", "Staudinger", "Steger", "Steinbauer", "Steinberger", "Steindl", "Steiner", "Steininger", "Steinkellner", "Steinlechner", "Steinwender", "Stelzer", "Stern", "Steurer", "Stocker", "Stockinger", "Strasser", "Strauss", "Strauß", "Strobl", "Stummer", "Sturm", "Stöckl", "Stöger", "Suppan", "Swoboda", "Szabo",
		"Thaler", "Thaller", "Thurner", "Theurl", "Tischler", "Toth", "Traxler", "Trimmel", "Trummer",
		"Ulrich", "Unger", "Unterberger", "Unterweger", "Urban",
		"Varga", "Vodiunig", "Vogel", "Vogl",
		"Wachter", "Wadl", "Wagner", "Walch", "Walcher", "Wallner", "Walter", "Weber", "Wechselberger", "Wegscheider", "Weidinger", "Weigl", "Weinberger", "Weiss", "Weiß", "Weninger", "Werner", "Wernig", "Wieland", "Wieser", "Wiesinger", "Wild", "Wilhelm", "Wimmer", "Windisch", "Winkler", "Winter", "Wirth", "Wittmann", "Wolf", "Wurm", "Wurzer",
		"Zach", "Zangerl", "Zauner", "Zechner", "Zehetner", "Zeilinger", "Zeller", "Zenz", "Ziegler", "Zimmermann", "Zöhrer",
	}
)
