package namegen

var (
	indonesianFemaleFirstNames = []string{
		"Ade", "Adinda", "Adriani", "Afni", "Afriani", "Agnes", "Agustian", "Agustin", "Agustina", "Agustini", "Aini", "Ajeng", "Amalia", "Ambar", "Ambarwati", "Amelia",
		"Amanda", "Ana", "Ananda", "Anastasia", "Andina", "Andini", "Andriana", "Andriani", "Andriyani", "Angelia", "Angelina", "Anggi",
		"Anggia", "Anggit", "Anggita", "Anggraeni", "Anggraini", "Anggun", "Ani", "Anik", "Anindita", "Anita", "Anna", "Apriani",
		"Aprilia", "Apriyani", "Apriyanti", "Ari", "Aria", "Ariani", "Arie", "Arini", "Arista", "Ariyani", "Ariyanti", "Arum",
		"Ary", "Aryani", "Asih", "Asmara", "Asri", "Asti", "Astri", "Astria", "Astrid", "Astuti", "Atik", "Atika", "Ayu",
		"Ayuningtyas", "Betty", "Bunga", "Cahya", "Cahyani", "Carolina", "Christin", "Christina", "Christine", "Christy", "Cindy",
		"Citra", "Cut", "Dahlia", "Damayanti", "Dani", "Darma", "Deasy", "Debby", "Debora", "Dede", "Desi", "Dessy", "Desti",
		"Desty", "Desy", "Devi", "Devita", "Devy", "Dewi", "Dhani", "Dharma", "Dhian", "Diah", "Dian", "Diana", "Dika", "Dina",
		"Dinda", "Dini", "Dita", "Diyah", "Dona", "Dwi", "Dyah", "Dyan", "Eka", "Ekawati", "Elfrida", "Eli", "Elisa", "Elisabeth",
		"Eliza", "Elly", "Elsa", "Ema", "Emi", "Emy", "Endah", "Endang", "Eni", "Eny", "Eri", "Erika", "Erlina", "Erma", "Erna",
		"Ernawati", "Erni", "Ervina", "Ester", "Esti", "Eva", "Evi", "Evy", "Faizah", "Fanny", "Farah", "Farida", "Fatmawati",
		"Febri", "Febrian", "Febriana", "Febriani", "Febrianti", "Febrina", "Febriyanti", "Fenny", "Fera", "Fika", "Fina", "Fitri",
		"Fitria", "Fitriah", "Fitriana", "Fitriani", "Fitriyani", "Fransisca", "Fransiska", "Frida", "Friska", "Galuh", "Gina",
		"Gita", "Grace", "Hana", "Handayani", "Hani", "Hanna", "Hanny", "Hanum", "Happy", "Hapsari", "Hartati", "Hastuti",
		"Hayati", "Helmi", "Heni", "Henny", "Herawati", "Herlina", "Hesti", "Hilda", "Ida", "Iin", "Iis", "Ika", "Ike", "Ima",
		"Imelda", "Ina", "Indah", "Indrawati", "Indri", "Indriani", "Indriyani", "Intan", "Ira", "Irawati", "Irene", "Irma",
		"Irna", "Ita", "Jati", "Jayanti", "Juli", "Julia", "Juliana", "Julianti", "Juni", "Junita", "Juwita", "Kadek", "Karina",
		"Karlina", "Kartika", "Kartikasari", "Kartini", "Kharisma", "Kiki", "Komalasari", "Kristina", "Kumala", "Kumalasari",
		"Kurnia", "Kurniasari", "Kurniasih", "Kurniati", "Kurniawan", "Kurniawati", "Kusuma", "Kusumastuti", "Kusumawati",
		"Laila", "Laili", "Larasati", "Laura", "Leni", "Lenny", "Leny", "Lestari", "Lia", "Lidia", "Lidya", "Lilik", "Lilis",
		"Lina", "Linda", "Lisa", "Listya", "Lita", "Liza", "Lucky", "Lusiana", "Lydia", "Made", "Magdalena", "Maharani",
		"Mandasari", "Mardiana", "Margaretha", "Maria", "Mariana", "Marina", "Marisa", "Marissa", "Marlina", "Marta",
		"Martha", "Martin", "Martina", "Maryati", "Maulida", "Maulina", "Maya", "Mayang", "Mayasari", "Mega", "Megasari",
		"Megawati", "Mei", "Meita", "Melati", "Melinda", "Melisa", "Merry", "Meutia", "Mia", "Mila", "Mira", "Miranti",
		"Mirza", "Mita", "Mulia", "Mulya", "Mulyani", "Murni", "Murti", "Mustika", "Mutia", "Mutiara", "Nadia", "Nadya",
		"Nana", "Nanda", "Nani", "Nanik", "Natalia", "Nelly", "Neni", "Nia", "Niken", "Nila", "Nina", "Ningrum", "Ningsih",
		"Nirmala", "Nisa", "Nita", "Noni", "Noor", "Nora", "Norma", "Nova", "Novalia", "Novi", "Novia", "Noviana", "Noviani",
		"Novianti", "Novita", "Novitasari", "Noviyanti", "Nugraheni", "Nur", "Nuraeni", "Nuraini", "Nurina", "Nurmala",
		"Nurul", "Octavia", "Octaviani", "Okta", "Oktarina", "Oktavia", "Oktaviana", "Oktaviani", "Olivia", "Palupi",
		"Paramita", "Paramitha", "Permata", "Permatasari", "Pertiwi", "Pipit", "Poppy", "Pradipta", "Pramita", "Pratiwi",
		"Prima", "Prita", "Puji", "Purba", "Puri", "Purnama", "Purnamasari", "Purwaningsih", "Purwanti", "Puspa", "Puspasari",
		"Puspita", "Puspitasari", "Puti", "Putri", "Putu", "Rachma", "Rachmawati", "Ragil", "Rahayu", "Rahma", "Rahmadhani",
		"Rahmah", "Rahmawati", "Rahmi", "Rani", "Rara", "Ratih", "Ratna", "Ratnasari", "Ratnawati", "Ratri", "Ratu", "Regina",
		"Reni", "Renny", "Reny", "Resti", "Restu", "Retno", "Reza", "Ria", "Riana", "Riani", "Rika", "Rima", "Rina", "Rini",
		"Riri", "Ririn", "Risa", "Riska", "Riski", "Risky", "Risma", "Risna", "Rita", "Riza", "Rizka", "Rizki", "Rizky", "Rizqi",
		"Roro", "Rosa", "Rosalina", "Rosdiana", "Rosita", "Rully", "Ruth", "Safitri", "Sandra", "Sani", "Santi", "Santy",
		"Saputri", "Sarah", "Saraswati", "Sari", "Sartika", "Savitri", "Sekar", "Selly", "Senja", "Septi", "Septiani", "Setia",
		"Setiawati", "Setyaningsih", "Setyowati", "Shinta", "Silvia", "Sinta", "Siska", "Siti", "Sitti", "Soraya", "Sri",
		"Suci", "Sukma", "Sukmawati", "Sulistyowati", "Sundari", "Suryani", "Susanti", "Susi", "Susilowati", "Tantri", "Tia",
		"Tiara", "Tika", "Tirta", "Tita", "Titi", "Titik", "Titin", "Titis", "Tri", "Tria", "Triana", "Trisna", "Trisnawati",
		"Tuti", "Tyas", "Ulfa", "Ulfah", "Utami", "Utari", "Vera", "Veronica", "Veronika", "Vidya", "Vina", "Vita", "Vivi",
		"Wahyuni", "Wahyuningsih", "Wanda", "Wardani", "Wardhani", "Wati", "Wawan", "Wayan", "Wenny", "Widhi", "Widi", "Widia",
		"Widiastuti", "Widya", "Widyaningrum", "Widyastuti", "Wijayanti", "Wina", "Winda", "Windi", "Windy", "Wiwik", "Wiwin",
		"Wulan", "Wulandari", "Wulansari", "Wuri", "Yani", "Yanti", "Yayuk", "Yeni", "Yenni", "Yenny", "Yohana", "Yolanda",
		"Yuanita", "Yuli", "Yulia", "Yuliana", "Yuliani", "Yulianti", "Yulita", "Yuni", "Yunia", "Yuniar", "Yuniarti", "Yunita",
		"Yusnita", "Yuyun",
	}

	indonesianMaleFirstNames = []string{
		"Aan", "Ade", "Adhi", "Adhitya", "Adi", "Aditia", "Aditya", "Adityo", "Adrian", "Ady", "Afrizal", "Agung",
		"Agus", "Agustian", "Agustinus", "Aji", "Alam", "Alamsyah", "Alfian", "Ali", "Ananda",
		"Anang", "Andhika", "Andi", "Andika", "Andre", "Andreas", "Andri", "Andrian", "Andry", "Andy", "Angga",
		"Anggara", "Anggoro", "Anjar", "Anton", "Anugrah", "Anwar", "Aprianto", "Ardi", "Ardian", "Ardiansyah", "Ari", "Aria",
		"Arie", "Aries", "Ario", "Aris", "Arisandi", "Ariyanto", "Artha", "Ary", "Arya", "Aryo", "Asep", "Bagus", "Bahri",
		"Baiq", "Bambang", "Bangun", "Baskoro", "Bayu", "Benny", "Bima", "Bintang", "Bobby", "Budi", "Budiman",
		"Cahyadi", "Cahyo", "Cahyono", "Candra", "Catur", "Chandra", "Dadang", "Danang", "Dani", "Daniel", "Danu", "Darma",
		"Darmawan", "David", "Deddy", "Dede", "Dedi", "Dedy", "Deni", "Denny", "Deny", "Dewa", "Dhani", "Dharma", "Dicky",
		"Didi", "Didik", "Dika", "Dimas", "Dinar", "Dodi", "Dody", "Doni", "Donny", "Dony", "Dwi", "Eddy", "Edi", "Edwin",
		"Edy", "Efendi", "Effendi", "Eka", "Eko", "Eri", "Erik", "Erwin", "Fadli", "Faisal", "Faizal", "Fajar", "Fajri",
		"Febri", "Febrian", "Febrianto", "Feri", "Fernando", "Ferry", "Fikri", "Firman", "Firmansyah", "Fitra", "Fitrah",
		"Galih", "Galuh", "Gede", "Gilang", "Ginanjar", "Ginting", "Gultom", "Gunawan", "Guntur", "Gusti", "Hadi", "Hakim",
		"Halim", "Handoko", "Hani", "Hari", "Haris", "Harry", "Hartanto", "Hartono", "Hary", "Haryanto", "Haryo", "Helmi",
		"Hendi", "Hendra", "Hendri", "Hendrik", "Hendro", "Hendy", "Henry", "Heri", "Herman", "Hermanto", "Hermawan", "Herry",
		"Heru", "Hery", "Himawan", "Huda", "Indra", "Indrawan", "Irawan", "Irfan", "Irvan", "Irwan", "Iskandar", "Ivan", "Iwan",
		"Januar", "Jati", "Jaya", "Johan", "Joko", "Kadek", "Ketut", "Komang", "Krisna", "Kukuh", "Leonardo", "Lucky", "Lumban",
		"Made", "Mahardika", "Mahendra", "Martin", "Michael", "Mukti", "Mulia", "Mulya", "Nanang", "Nanda", "Noor", "Nova",
		"Nugraha", "Nugroho", "Nur", "Nyoman", "Okta", "Pandu", "Panji", "Permata", "Prabowo", "Pradana", "Pradipta", "Pramono",
		"Prasetya", "Prasetyo", "Pratama", "Pratomo", "Pribadi", "Prima", "Priyo", "Puji", "Purba", "Purnama", "Purnomo",
		"Purwanto", "Putra", "Putro", "Rachmad", "Rachmat", "Raditya", "Ragil", "Rahadian", "Rahardian", "Rahmad", "Rama", "Randy", "Rangga",
		"Rendy", "Restu", "Reza", "Rian", "Ricky", "Ridha", "Ridho", "Ridwan", "Rifki", "Riki", "Rinaldi", "Rio", "Riski", "Risky",
		"Riyadi", "Riyanto", "Rizal", "Rizki", "Rizky", "Rizqi", "Robby", "Romi", "Ronald", "Roni", "Rony", "Roy", "Roza", "Rudi",
		"Rudy", "Rully", "Ryan", "Sahat", "Sakti", "Samuel", "Sandi", "Sandy", "Sanjaya", "Santoso", "Sapta", "Sapto", "Saputra",
		"Saputro", "Satria", "Satrio", "Satya", "Septian", "Septiana", "Setia", "Setiadi", "Setiawan", "Seto", "Setya", "Setyawan",
		"Setyo", "Sigit", "Slamet", "Sofyan", "Sugeng", "Sulastri", "Sulistyo", "Supriyanto", "Surya", "Suryadi", "Suryo", "Susanto",
		"Susilo", "Sutrisno", "Syah", "Syahputra", "Syahrul", "Syaiful", "Syam", "Syamsul", "Teguh", "Tommy", "Toni", "Tri", "Tria",
		"Tulus", "Utama", "Utomo", "Wahyu", "Wahyudi", "Wardhana", "Wibisono", "Wibowo", "Wicaksono", "Widhi", "Widi", "Widodo",
		"Wijaya", "Wijayanto", "Willy", "Wira", "Wirawan", "Wisnu", "Yan", "Yanuar", "Yoga", "Yogi", "Yohanes", "Yuda", "Yudha",
		"Yudhi", "Yudi", "Yulianto", "Genta", "Gibran", "Panca", "Raka",
	}

	indonesianLastNames = []string{
		"Adhitya", "Aditia", "Aditya", "Adityo", "Adrian", "Agung", "Agustian", "Agustinus", "Alamsyah", "Ananda", "Andhika", "Andika",
		"Andreas", "Andrian", "Anggara", "Anggoro", "Anugrah", "Aprianto", "Ardian", "Ardiansyah", "Aria", "Aries", "Ario", "Arisandi",
		"Ariyanto", "Bambang", "Bangun", "Baskoro", "Budiman", "Cahyadi", "Cahyo", "Cahyono", "Candra", "Catur", "Chandra", "Dadang",
		"Danang", "Dani", "Daniel", "Danu", "Darmawan", "David", "Dhani", "Dimas", "Edwin", "Efendi", "Effendi", "Faisal", "Faizal",
		"Fajar", "Fajri", "Febrian", "Febrianto", "Fernando", "Firmansyah", "Gilang", "Ginanjar", "Ginting", "Gunawan", "Hakim",
		"Halim", "Handoko", "Hartanto", "Hartono", "Haryanto", "Hendi", "Hendra", "Hendri", "Hendrik", "Hendro", "Hendy", "Henry",
		"Herman", "Hermanto", "Hermawan", "Herry", "Himawan", "Huda", "Indra", "Indrawan", "Irawan", "Irfan", "Iskandar", "Januar",
		"Leonardo", "Mahardika", "Mahendra", "Martin", "Michael", "Mukti", "Mulia", "Mulya", "Nugraha", "Nugroho", "Panji", "Permata",
		"Prabowo", "Pradana", "Pradipta", "Pramono", "Prasetya", "Prasetyo", "Pratama", "Pratomo", "Pribadi", "Prima", "Priyo",
		"Purnama", "Purnomo", "Purwanto", "Rachmad", "Rachmat", "Raditya", "Ragil", "Rahadian", "Rahmad", "Rangga", "Ridwan", "Rinaldi",
		"Riyadi", "Riyanto", "Rizki", "Rizky", "Rizqi", "Samuel", "Sanjaya", "Santoso", "Saputra", "Saputro", "Satria", "Satrio", "Satya",
		"Septian", "Septiana", "Setia", "Setiadi", "Setiawan", "Setyawan", "Sofyan", "Sugeng", "Sulastri", "Sulistyo", "Supriyanto",
		"Suryadi", "Susanto", "Susilo", "Sutrisno", "Syahputra", "Syahrul", "Syaiful", "Syam", "Utama", "Utomo", "Wahyudi", "Wardhana",
		"Wibisono", "Wibowo", "Wicaksono", "Widodo", "Wijaya", "Wijayanto", "Wirawan", "Yanuar", "Yohanes", "Yulianto", "Dirga", "Perdana", "Pramana",
	}
)
