package namegen

var (
	irishFemaleFirstNames = []string{
		"Aibhilín",
		"Aifric",
		"Aíbhinn",
		"Ailbhe",
		"Áine",
		"Aisling",
		"Aithche",
		"Aodhamair",
		"Aodhnait",
		"Aoibheann",
		"Aoife",
		"Aoileann",
		"Athracht",
		"Barrdhubh",
		"Bébhinn",
		"Bláth",
		"Blinne",
		"Bríd",
		"Brónach",
		"Buadhnait",
		"Cacht",
		"Caoimhe",
		"Caoilfhionn",
		"Ciamhnait",
		"Ciannait",
		"Ciara",
		"Clíona",
		"Clodagh",
		"Cobhlaith",
		"Damhnait",
		"Dearbháil",
		"Dearbhfhorgaill",
		"Deirbhile",
		"Deirdre",
		"Dianaimh",
		"Doireann",
		"Dubhchobhlaigh",
		"Dubhóg",
		"Éabha",
		"Ealga",
		"Earnait",
		"Easnadh",
		"Éibhleann",
		"Eithne",
		"Éimhear",
		"Éadaoin",
		"Étaín",
		"Faoiltighearna",
		"Feidhelm",
		"Féthnaid",
		"Féthnat",
		"Fiadh",
		"Fiadhnait",
		"Fíona",
		"Fionnabhair",
		"Fionnuala",
		"Flann",
		"Flannait",
		"Fodhla",
		"Forbhlaith",
		"Fíneamhain",
		"Geiléis",
		"Gobnait",
		"Gormlaith",
		"Gráinne",
		"Iodhnait",
		"Íde",
		"Lann",
		"Lasairfhíona",
		"Meabh",
		"Mealla",
		"Míde",
		"Mór",
		"Móirín",
		"Míonait",
		"Muadhnait",
		"Muireann",
		"Muirinn",
		"Muirgheal",
		"Muirne",
		"Naoise",
		"Neasa",
		"Niamh",
		"Nollaig",
		"Nuala",
		"Nóra",
		"Nóirín",
		"Órnait",
		"Onóra",
		"Órla",
		"Peig",
		"Peigín",
		"Rathnait",
		"Ríona",
		"Róisín",
		"Sadhbh",
		"Saoirse",
		"Saorla",
		"Siofra",
		"Síthmaith",
		"Sláine",
		"Sorcha",
		"Tuathflaith",
		"Uainionn",
		"Uallach",
		"Uasal",
		"Úna",
	}

	irishMaleFirstNames = []string{
		"Abbán",
		"Aibhne",
		"Ailín",
		"Ailbhe",
		"Ailill",
		"Ainníleas",
		"Amhalgaidh",
		"Anluan",
		"Anmchadh",
		"Aodh",
		"Aodhán",
		"Aogán",
		"Aonghus",
		"Árdghal",
		"Art",
		"Barra",
		"Baothghalach",
		"Beacán",
		"Bearchán",
		"Bran",
		"Breasal",
		"Breandán",
		"Brian",
		"Brochadh",
		"Buadhach",
		"Cailean",
		"Cairbre",
		"Calbhach",
		"Caoimhín",
		"Caolán",
		"Caomhán",
		"Carraig",
		"Cárthach",
		"Cathal",
		"Cathaoir",
		"Cathbharr",
		"Ceallach",
		"Ceallachán",
		"Cearbhall",
		"Cían",
		"Cíanán",
		"Ciarán",
		"Cinnéididh",
		"Cionaodh",
		"Ciothruadh",
		"Cillian",
		"Coinneach",
		"Coireall",
		"Colla",
		"Colm",
		"Colmán",
		"Comán",
		"Comhghall",
		"Comhghan",
		"Conall",
		"Conán",
		"Conaire",
		"Conchúr",
		"Conghalach",
		"Conmhac",
		"Conn",
		"Connla",
		"Connlaodh",
		"Cormac",
		"Cosnamhach",
		"Criomthann",
		"Cróchán",
		"Crónán",
		"Cuan",
		"Cúchonnacht",
		"Cuimín",
		"Cúmhaighe",
		"Cúmheadha",
		"Dabhag",
		"Daibhí",
		"Damháin",
		"Dara",
		"Déaglán",
		"Deasmhumhnach",
		"Diarmaid",
		"Dónall",
		"Donn",
		"Donnghaile",
		"Donnchadh",
		"Dubhaltach",
		"Dubhán",
		"Dubhghall",
		"Dubhghlas",
		"Dúnlang",
		"Eachaidh",
		"Eachann",
		"Eachthighearn",
		"Éanán",
		"Éanna",
		"Earcán",
		"Earnán",
		"Éibhear",
		"Éignach",
		"Éimhín",
		"Éireamhón",
		"Eochaidh",
		"Eoghan",
		"Fachtna",
		"Fáilbhe",
		"Faolán",
		"Fearadhach",
		"Fearchar",
		"Feardorcha",
		"Fearganainm",
		"Fearghal",
		"Feichín",
		"Féilim",
		"Fergus",
		"Fiach",
		"Finghin",
		"Fionghuine",
		"Fionn",
		"Fionnbharr",
		"Fitheal",
		"Flann",
		"Garbhán",
		"Glaisne",
		"Iarlaith",
		"Irial",
		"Lachtna",
		"Laoiseach",
		"Lasairian",
		"Lochlann",
		"Lomán",
		"Lonán",
		"Lorcán",
		"Lughaidh",
		"Maeleachlainn",
		"Maelíosa",
		"Mainchín",
		"Maodhóg",
		"Maoilín",
		"Maoilir",
		"Maolcholm",
		"Maolmórdha",
		"Maolmhuire",
		"Maolruadháin",
		"Marcus",
		"Mathghamhain",
		"Muircheartach",
		"Muireadhach",
		"Muirgheas",
		"Murchadh",
		"Naomhán",
		"Naoise",
		"Naos",
		"Neachtan",
		"Neasán",
		"Niall",
		"Nollaig",
		"Odhrán",
		"Oireachtach",
		"Oisín",
		"Oscar",
		"Riain",
		"Roibhilín",
		"Rónán",
		"Ros",
		"Ruadhán",
		"Ruairí",
		"Saerbhreathach",
		"Sechnassach",
		"Seachnasach",
		"Séadna",
		"Senán",
		"Siadhal",
		"Sioda",
		"Suibhne",
		"Tadhg",
		"Taichleach",
		"Tighernach",
		"Toirdhealbhach",
		"Toirleach",
		"Torna",
		"Treabhair",
		"Tuathal",
		"Uaitéar",
		"Uaithne",
		"Ualgharg",
		"Ultán",
	}

	irishLastNames = []string{
		"Mac an Bhreitheamhan", "Ó hEachthianna", "Mac an tSaoir",
		"Mac Amhalghaidh", "Mac Amhlaoibh",
		"Mac Árdghail", "Ó Banain", "Ó Beaglaoich", "Ó Birn",
		"Ó hAimheirgin", "Ó Beolláin", "Ó Baoghill",
		"Ó Baoighealláin", "Mac Bradaigh", "Ó Brollacháin",
		"Mac Braoin", "Ó Braoin", "Mac an Bhreitheamhnaigh",
		"Mac Branain", "Ó Braonain", "Ó Breislein", "Ó Bric",
		"Ó Bruic", "Mac Giolla", "Ó Briain", "Ó Bruadiar",
		"Ó Brógáin", "Ó Brolaigh", "Ó Bróithe", "Ó Brosnacháin", "Ó Buachalla", "Ó Bogaigh", "Mac Conboirne", "Ó Broin",
		"Mac Cába", "Mac Gafraidh", "Ó Cathain", "Ó Cathail",
		"Ó Ceallacháin", "Ó Cathaláin", "Mac Giolla Laoire", "Mac Cathmhaoil",
		"Mac Cailein", "Ó Ceanndubháin", "Mac Cuindlis", "Mac Anna",
		"Ó Canain", "Ó Canannain", "Ó Caithniadh", "Ó an Cháintigh",
		"Ó Cairbre", "Ó Ciardha", "Ó Cearmada", "Mac Cearnaigh",
		"Ó Cearrnaigh", "Ó Cairealláin", "Ó Cearbhalláin", "Ó Cairre",
		"Ó Cearbhaill", "Mac Cearbhaill", "Mac Artian", "Mac Carthaigh", "Ó Cathasaigh",
		"Mac Cathasaigh", "Ó Caiside", "Mac Fhlannchaidh",
		"Ó Cleireigh", "Ó Cléirigh", "Ó Cleirchín", "Ó Clochasaigh", "Mac Cluin",
		"Mac Bhloscaidh", "Ó Cobhthaigh", "Mac Cagadhain",
		"Ó Colmáin", "Ó Clúmháin", "Mac Colghain", "Ó Colghain", "Ó Coileáin",
		"Ó Cuilleáin", "Ó Concheannain", "Ó Caoindealbháin",
		"Ó Connalláin", "Ó Coinghiolláin", "Mac Conghaile", "Ó Conaill",
		"Mac Dhomhnaill", "Ó Conghailaigh", "Ó Conghalaigh",
		"Ó Coingheallaigh", "Ó Congalaig", "Mac Canann", "Conchobhair",
		"Ó Maolconaire", "Ó Conraoi", "Mac Conraoi", "Mac Consaidín",
		"Mac Conmhaoil", "Ó Conbhuidhe", "Ó Connmhacháin", "Mac Connmhaigh",
		"Mac Conmidhe", "Mac Congail", "Ó Cuagain", "Mac Cuille",
		"Ó Cuana", "Ó Culachain", "Mac Corcrain", "Ó Corcráin", "Mac Cormac",
		"Ó Corraidh", "Ó Corragáin", "Ó Cosraigh", "Mac Oistoghín",
		"Mac Oitir", "Mac Cochláin", "Ó Cochláin", "Mac Coibheanaigh", "Ó Cadhain",
		"Mac Ruidhri", "Craobhach", "Ó Croidheáin", "Ó Creacháin",
		"Ó Criocháin", "Mac Conchruachan", "Mac Criomhthainn",
		"Ó Croinin", "Ó Cruadhlaoich", "Ó Cuidighthigh",
		"Ó Cuilinn", "Ó Cuileannáin", "Ó Coimín", "Mac Coinín", "Ó Coinín", "Ó Connagáin",
		"Mac Toirdhealbhaigh", "Ó Curráin", "Ó Corraidhin", "Mac Curtain",
		"Mac Cosraigh", "Ó Comhraidhe", "Ó Dalaigh", "Ó Dorchaidhe",
		"Ó Duibhdabhoireann", "Ó Deághaidh", "Ó Dulchaointigh", "Ó Dubhshláine",
		"Ó Diomasaigh", "Ó Duineachdha", "Ó Duibhdíorma",
		"Mac Diarmada", "Ó Duibheamhna", "Ó Duibhghiolla", "Ó Daimhín", "Ó Doibhilin",
		"Ó Dubhuidhe", "Ó Duilleain", "Ó Daighnáin",
		"Ó Duinnín", "MacDail re Deachair", "Ó Dubhchonna", "Ó Dochartaigh", "Ó Dubhhláin",
		"Ó Domhnallain", "Mac Donnchadha", "Ó Donnagáin",
		"Mac Duinnshléibhe", "Mac Domhnaill", "Ó Domhnaill",
		"Ó Domhnalláin", "Ó Donnghaile", "Ó Donnchadha",
		"Ó Donndubháin", "Ó Duacháin", "Ó Duighlaich",
		"Ó Deoráin", "Ó Deargáin", "Ó Dudbhchon", "Ó Dubhda", "Ó Dunlaing",
		"Ó Dúnadhaigh", "Ó Dubhghaill", "Ó hEidirsceoil",
		"Ó Diubháin", "Ó Dubhthaigh", "Ó Dubhagáin", "Ó Diubhgeannáin", "Ó Doinn", "Ó Duibhir",
		"Mac Aodhagáin", "Mac Giolla Domhaigh", "Mac Giolla Rua", "Mac Conchradha",
		"Mac Inneirghe", "Ó hAonghuis", "Mac Fhiodhbhuidhe",
		"O Faodhagáin", "Ó Fathaigh", "Ó Fallamháin", "Ó Failbhe", "Ó Fhearghaill",
		"Ó Faircheallaigh", "Ó Faracháin", "Ó Fearáin", "Ó Fiannaidhe", "Ó Fidhne",
		"Ó Fithcheallaigh", "Ó Fiachna", "Ó Fiachra", "Ó Fionnaláin",
		"Ó Fiangusa", "Ó Fearadhaigh", "Ó Fionnachta", "Ó Fionnáin",
		"Ó Fionn", "Ó Fionnagáin", "Ó Finntighearn", "Mac Fionbhair",
		"Mac Giolla Mocholmog", "Mac Giolla Phadraig", "Ó Flaithbheartach", "Ó Flannagáin",
		"Ó Flannabhra", "Ó Flaithre", "Ó Floinn", "Ó Flainn", "Ó Fhloinn", "Ó Fhógartaigh",
		"Ó Foghladha", "Mac Giolla na Naomh", "Mac Conshnámha", "Ó Fuaráin",
		"Macgiollarnath", "Mac An tSionnaigh", "Ó Firghil", "Ó Gamhna", "Mac Carrghamhna",
		"Mac Conghamhma", "Ó Gallchobhair", "Mac Giolla Riabhaigh", "Ó Gealbháin",
		"Ó Gaibhtheacháin", "Mag Fhionnáin", "Ó Gadhra", "Mag Fhearadhaigh", "Ó Gairbhith",
		"Ó Gairbhín", "Ó Garbháin", "Mac Gairbhín", "Mag Aodha",
		"Mag Aonghusa", "Mag Eochagáin", "Mag Oireachtaigh",
		"Mac Giolla Phóil", "Mac Giolla Mochuda", "Ó Glaimhin", "Ó Glesáin", "Mag Fhloinn",
		"Ó Gradaigh", "Mac Gormain", "Ó Gairmleadhaigh", "Mag Shamhradháin", "Mac Gabhann", "Ó Grádaigh",
		"Mac Raith", "Ó hUaithnigh", "Mac Glaisin", "Ó Griobhtha",
		"MagUiginn", "Mac Aonghasa", "Mag Uidhir", "Ó hÉidin", "Ó hAodhagáin", "Mac Céile", "Ó haileacháin",
		"Ó hAileagáin", "Ó hAllmhuráin", "Ó hAghmaill",
		"Ó hÁinle", "Ó hAnluain", "Ó hAnnáin", "Ó hAnrachain", "Ó hAnrachtaigh", "Ó hEaghra", "Ó hÍr",
		"Ó hEarcáin", "Ó hAirt", "Ó hIongardail", "Ó hArrachtain",
		"Ó hArtagáin", "Ó hEidedín", "Ó hAodha", "Ó hEilidhe", "Ó hEaladaighthe", "Ó hÉalaighthe", "Ó hÉignigh",
		"Ó hEachighearna", "Ó hEadroman", "Ó hIfearnáin",
		"Ó hEigceartaigh", "Ó hAichir", "Ó hAonghusa", "Ó hInneirghe",
		"Ó hAiniarriadh", "Mac Einri", "Ó hOireachtaigh",
		"Ó hEisleanáin", "Ó hIcidhe", "Ó hUigín",
		"Ó hÓgáin", "Ó hUallacháin", "Ó hEoghanáin", "Ó hUaithnín",
		"Ó hOdhráin", "Mac Aodha", "Ó Urthaile",
		"Ó hUirthile", "Ó hIarlatha", "Ó hEidhin",
		"Mac Giolla Bháin", "Mac Giolla Ruadh", "Mac an Airchinnigh",
		"Caomhanach", "Ó Cadhla", "Ó Caollaidhe",
		"Ó Cein", "Ó Catharnaigh", "Ó Géibheannaigh", "Ó Caoimh", "Ó Cianáin",
		"Ó Caomháin", "Ó Céileachair", "Ó Ceallaigh", "Ó Caellaighe", "Mac Cionath",
		"Ó Cinnéide", "Ó Cionnaoith", "Ó Caoinnigh", "Ó Coinne",
		"Mac Eochaidh", "Mac Eoghain", "Ó Ciabháin", "Ó Céirín", "Ó Ciarain",
		"Ó Cinnfhaelidh", "Chennselaig", "Ó Ciardubháin", "Ó Leathlaobhair",
		"Ó Longáin", "Ó Lonagáin", "Ó Lorcáin", "Mac Lochlainn", "Ó fLaithbheartaigh", "Ó Limhain", "Ó Laochdha",
		"Ó Laoghaire", "Ó Léanacháin", "Ó Leannain", "Mac Giolla Mhín",
		"Ó Longargain", "Ó Longain", "Ó Longaigh", "Ó Lochlainn",
		"Ó Maoilsheachlainn", "Ó Labhradha", "Ó Lúinigh", "Ó Loideáin",
		"Ó Loinsigh", "Ó Laighin", "Ó Liatháin", "Mac Maolruanaidh",
		"Ó Macdha", "Ó Madaidhin", "Ó Meachair", "Mac Mathghamha", "Ó Mathghamhna", "Ó Máille", "Ó Maoil Eoin", "Ó Maoileoin",
		"Ó Mainnín", "Mac Maghnais", "Ó Meadhra", "Mac Giolla Mhartain", "Ó Miadhachain",
		"Ó Midhir", "Ó Mealláin", "Ó Maoilédigh", "MacMeanman", "Ó Muilleoir",
		"Ó Mochain", "Ó Maolmhuaidh", "Ó Maoil Aodha",
		"Ó Maol Dhómhnaigh", "Ó Manachain", "Ó Maonaigh", "Ó Móráin",
		"Ó Mughráin", "Ó Mórdha", "Ó Murchain", "Ó Muircheartaigh",
		"Ó Muirgheasa", "Ó Maolchathaigh", "Ó Maoldúin", "Ó Maoldoraidh",
		"Ó Maoldomhnaigh", "Ó Maolchathail", "Ó Maolchalann", "Maoilchiaráin", "Ó Maolalaidhs", "Ó Maolain", "Ó Maolagáin", "Ó Maolchaoine",
		"Ó Maolruanaidh", "Ó Maoilriaghain", "Ó Murnain", "Mac Murchada", "Ó Murchadha",
		"Ó Muireachaidh", "Ó Muireadhaigh", "Mac Muireachaidh",
		"Mac an Fhailghigh", "Mac Con Uladh", "Mac Conmara",
		"Ó Neachtain", "Ó Neill", "Mac an Fhilidh",
		"Ó Niallain", "Ó Nuallain", "Ó hIonmhaineáin", "Mac Phaidin", "Ó Peatáin",
		"Ó Faolain", "Ó Coigligh", "Ó Cuill", "Mac an Choilgh", "Ó Cuinn",
		"Ó Cuirc", "Ó Raithbheartiagh", "Mac Raghnaill",
		"Ó Reachtagáin", "Ó Riordan", "Ó Rodáin", "Ó Riagáin", "Ó Raogáin",
		"Ó Riada", "Ó Raghallaigh", "Ó Maolcraoibhe", "Ó Ruanaidh", "Ó Roghan",
		"Mac Ruaidhri", "Ó Ruairc", "Ó Ruaidhín", "Ó Ruadháin",
		"Ó Riaghain", "Ó Scannláin", "Mac Scannláin",
		"Ó Scolaidhe", "Ó Scolláin", "Ó Seasnáin", "Ó Seanachain", "Mac Seanlaoich", "Ó Seanáin",
		"Mac Giolla tSeanáin", "Mac Searraigh", "Ó Seachnasaigh", "Ó Seaghdha",
		"Ó Siodhacháin", "Ó Sirideáin", "Ó Seiridh", "Mac an Ghirr", "Ó Sluaghain", "Ó Sóchlacháin", "Ó Spealáin",
		"Ó Suileabháin", "Mac Suibhne", "Ó Tarpaigh",
		"Mac Tighearnáin", "Ó Tighearnaigh", "Ó Tuathail",
		"Ó Treasaigh", "Mac Tréinfhir", "Ó Tiobraide", "Ó Tuama", "Mac an Bháird",
	}
)
