package namegen

var (
	japaneseMaleFirstNames = []string{
		"Akio",
		"Akira",
		"Akihiko",
		"Akito",
		"Aoi",
		"Aoki",
		"Arata",
		"Asahi",
		"Atsushi",
		"Botan",
		"Chikao",
		"Daichi",
		"Daigo",
		"Daijiro",
		"Daiki",
		"Daisuke",
		"Fuji",
		"Genkei",
		"Goro",
		"Haruki",
		"Hideki",
		"Hikaru",
		"Hiro",
		"Hiroshi",
		"Hiroto",
		"Habiki",
		"Hachirou",
		"Haru",
		"Haruto",
		"Hayate",
		"Hayato",
		"Hideaki",
		"Hideyoshi",
		"Hiroyoshi",
		"Hotaka",
		"Hotaru",
		"Ichiro",
		"Itachi",
		"Itsuki",
		"Jiro",
		"Kenji",
		"Kiyoshi",
		"Kaito",
		"Katsu",
		"Katsuo",
		"Kazuhito",
		"Kazuki",
		"Kazuya",
		"Keiji",
		"Keisuke",
		"Keitaro",
		"Kin",
		"Kohaku",
		"Kohei",
		"Kosuke",
		"Kota",
		"Kouji",
		"Kouki",
		"Kuro",
		"Kyo",
		"Kyosuke",
		"Minoru",
		"Mako",
		"Makoto",
		"Masaru",
		"Masashi",
		"Matsu",
		"Naoki",
		"Naruto",
		"Natsu",
		"Nobu",
		"Oda",
		"Raiden",
		"Ren",
		"Ryu",
		"Rokuro",
		"Ryo",
		"Ryota",
		"Seiji",
		"Shoji",
		"Sanji",
		"Satoshi",
		"Shin",
		"Shinjiro",
		"Shiro",
		"Shohei",
		"Shota",
		"Shoyo",
		"Sora",
		"Taichi",
		"Taiki",
		"Takahiro",
		"Takashi",
		"Takato",
		"Takaya",
		"Takeshi",
		"Takuma",
		"Takumi",
		"Tetsuya",
		"Tobio",
		"Tomoya",
		"Tsuyoshi",
		"Wataru",
		"Yuki",
		"Yama",
		"Yamato",
		"Yasu",
		"Yasuo",
		"Yoshiki",
		"Yudai",
		"Yusei",
		"Yuto",
		"Yuya",
	}

	japaneseFemaleFirstNames = []string{
		"Yui",
		"Rio",
		"Yuna",
		"Hina",
		"Koharu",
		"Hinata",
		"Mei",
		"Mio",
		"Saki",
		"Miyu",
		"Kokona",
		"Haruka",
		"Rin",
		"Akari",
		"Yuna",
		"Honoka",
		"Momoka",
		"Aoi",
		"Ichika",
		"Sakura",
		"Himari",
		"Yume",
		"Airi",
		"Sara",
		"Nanami",
		"Ayaka",
		"Yuka",
		"Riko",
		"Noa",
		"Mao",
		"Yua",
		"Ayane ",
		"Hiyori",
		"Misaki",
		"Yuzuki",
		"Rina",
		"Sana",
		"Ría",
		"Ruka",
		"Kanon",
		"Kaho",
		"Hana",
		"Karin",
		"Risa",
		"Shiori",
		"Fuka",
		"Rino",
		"Anna",
		"Natsuki",
		"Nana",
		"Reina",
	}

	japaneseLastNames = []string{
		"Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto",
		"Nakamura", "Kobayashi", "Kato", "Yoshida", "Yamada", "Sasaki", "Yamaguchi", "Saito",
		"Matsumoto", "Inoue", "Kimura", "Hayashi", "Shimizu",
		"Yamazaki", "Mori", "Abe", "Ikeda", "Hashimoto",
		"Yamashita", "Ishikawa", "Nakajima", "Maeda", "Fujita", "Ogawa", "Goto", "Okada",
		"Hasegawa", "Murakami", "Kondo", "Ishii", "Saito", "Sakamoto", "Endo", "Aoki", "Fujii",
		"Nishimura", "Fukuda", "Ota", "Miura", "Fujiwara", "Okamoto", "Matsuda", "Nakagawa", "Nakano",
		"Harada", "Ono", "Tamura", "Takeuchi", "Kaneko", "Wada", "Nakayama", "Ishida", "Ueda",
		"Morita", "Hara", "Shibata", "Sakai", "Kudo", "Yokoyama", "Miyazaki", "Miyamoto", "Uchida",
		"Takagi", "Ando", "Taniguchi", "Ohno", "Maruyama", "Imai", "Takada", "Fujimoto", "Takeda",
		"Murata", "Ueno", "Sugiyama", "Masuda", "Sugawara", "Hirano", "Kojima", "Otsuka", "Chiba",
		"Kubo", "Matsui", "Iwasaki", "Sakurai", "Kinoshita", "Noguchi", "Matsuo", "Nomura", "Kikuchi",
		"Sano", "Onishi", "Sugimoto", "Arai",
	}
)
