package namegen

var (
	nigerianMaleFirstNames = []string{
		"Chinedu", "Oluwafemi", "Emeka", "Olumide", "Adeola", "Obinna", "Abdulahi", "Tunde", "Chijioke", "Oluwaseun",
		"Akin", "Nnamdi", "Babatunde", "Kunle", "Uche", "Oluwakayode", "Idris", "Chukwudi", "Yusuf", "Olufemi",
		"Kehinde", "Chigozie", "Taiwo", "Oluwatobi", "Adewale", "Eze", "Olamide", "Azeez", "Damilare", "Olatunji",
		"Adegoke", "Tochukwu", "Chuka", "Oluwatobiloba", "Ibrahim", "Oladapo", "Okechukwu", "Temitope", "Ezekiel", "Oluwadamilola",
		"Adeyemi", "Oluwatoyin", "Ifeanyi", "Onyekachi", "Osita", "Oluwafunmilayo", "Olabode", "Bolaji", "Olawale", "Chiemeka",
		"Oluwatosin", "Efe", "Obiora", "Olawunmi", "Olanrewaju", "Olusegun", "Tolulope", "Oluwadamisi", "Olayinka", "Oluwatoyosi",
		"Abiodun", "Olabisi", "Adebowale", "Olumuyiwa", "Olugbenga", "Chinonso", "Oluwaseyi", "Oluwafemi", "Oluseyi", "Olufunke",
		"Olumide", "Olujimi", "Adejare", "Adebayo", "Adeniyi", "Emmanuel", "Abraham", "Ademola", "Oluwaseun", "Elijah",
		"Joseph", "Joshua", "Gabriel", "Samuel", "Daniel", "David", "Michael", "Isaac", "Isaiah", "Stephen",
		"Andrew", "Matthew", "Mark", "John", "James", "Philip", "Thomas", "Paul", "Peter", "Nathan",
		"Nathaniel", "Simon", "Timothy", "Titus", "Ephraim", "Benjamin", "Samson", "Emeka", "Azubuike", "Chukwuemeka",
		"Chijindu", "Ogochukwu", "Chinweike", "Chukwubuikem", "Chinaza", "Chinedum", "Chibueze", "Chibuike", "Chibuzo", "Chijioke",
		"Chinwendu", "Chibundu", "Chukwunonso", "Chukwuweike", "Chukwudi", "Chukwuebuka", "Chukwuka", "Chibunna", "Chinemerem", "Chimaobi",
		"Chinonye", "Chukwunweike", "Chukwutoo", "Chukwuma", "Chinyelu", "Chisom", "Chibuzor", "Chukwudalu", "Chinomso", "Chukwunenye",
		"Chidubem", "Chukwukadibia", "Chibuihe", "Chidiebere", "Chigozirim", "Chizurum", "Chukwubuka", "Chijindum", "Chidinma", "Chinaza",
		"Chijiofor", "Chinweizu", "Chibuikem", "Chikamso", "Chikezie", "Chibueze", "Chukwumeka", "Chigozika", "Chikamara", "Chimaobim",
		"Chinonso", "Chinasa", "Chinelo", "Chukwuemeka", "Chukwuma", "Chizaram", "Chinwendu", "Chinedu", "Chigozie", "Chidiebere",
		"Chukwuebuka", "Chibundu", "Chinomnso", "Chibuihe", "Chukwuka", "Chukwunonso", "Chinonyelum", "Chibunna", "Chinaza", "Chukwudi",
		"Chibuzo", "Chijioke", "Chijindum", "Chinweike", "Chikamara", "Chikamso", "Chikezie", "Chimaobi", "Chimaobim", "Chinasa",
		"Chinelo", "Chinwendu", "Chinonso", "Chinomnso", "Chinonyelum", "Chukwubuka", "Chukwudi", "Chukwuebuka", "Chukwuka", "Chukwunonso",
		"Chukwunweike", "Chukwuma", "Chukwuweike", "Chukwutoo", "Chibuihe", "Chibundu", "Chibunna", "Chibuikem", "Chibuike", "Chibueze",
		"Chibueze", "Chibuike", "Chibuihe", "Chibundu", "Chibuikem", "Chibunna", "Chukwunonso", "Chukwutoo", "Chukwuma", "Chukwuweike",
		"Chukwuweike", "Chukwuemeka", "Chukwuka", "Chukwudi", "Chukwuebuka", "Chukwunonso", "Chukwunweike", "Chinedum", "Chinaza", "Chijindum",
		"Chinweike", "Chikamara", "Chikamso", "Chikezie", "Chikamso", "Chikezie", "Chibuike", "Chibueze", "Chibuzo", "Chijioke",
		"Chinwendu", "Chibundu", "Chukwunonso", "Chukwuweike", "Chukwudi", "Chukwuebuka", "Chibunna", "Chinemerem", "Chimaobi", "Chinonye",
		"Chukwunweike", "Chukwutoo", "Chukwuma", "Chinaza", "Chijiofor", "Chinweizu", "Chibuikem", "Chikamso", "Chikezie", "Chibueze",
		"Chukwumeka", "Chigozika", "Chikamara", "Chimaobim", "Chinonso", "Chinasa", "Chinelo", "Chukwuemeka", "Chukwuma", "Chizaram",
		"Chinwendu", "Chinedu", "Chigozie", "Chidiebere", "Chukwuebuka", "Chibundu", "Chinomnso", "Chibuihe", "Chukwuka", "Chukwunonso",
		"Chinonyelum", "Chibunna", "Chinaza", "Chukwudi", "Chibuzo", "Chijioke", "Chijindum", "Chinweike", "Chikamara", "Chikamso",
		"Chikezie", "Chimaobi", "Chimaobim", "Chinasa", "Chinelo", "Chinwendu", "Chinonso", "Chinomnso", "Chinonyelum", "Chukwubuka",
		"Chukwudi", "Chukwuebuka", "Chukwuka", "Chukwunonso", "Chukwunweike", "Chukwuma", "Chukwuweike", "Chukwutoo", "Chibuihe", "Chibundu",
		"Chibunna", "Chibuikem", "Chibuike", "Chibueze", "Chibueze", "Chibuike", "Chibuihe", "Chibundu", "Chibuikem", "Chibunna",
		"Chukwunonso", "Chukwutoo", "Chukwuma", "Chukwuweike", "Chukwuweike", "Chukwuemeka", "Chukwuka", "Chukwudi", "Chukwuebuka", "Chukwunonso",
		"Chukwunweike", "Chinedum", "Chinaza", "Chijindum", "Chinweike", "Chikamara", "Chikamso", "Chikezie", "Chikamso", "Chikezie",
		"Chibuike", "Chibueze", "Chibuzo", "Chijioke", "Chinwendu", "Chibundu", "Chukwunonso", "Chukwuweike", "Chukwudi", "Chukwuebuka",
		"Chibunna", "Chinemerem", "Chimaobi", "Chinonye", "Chukwunweike", "Chukwutoo", "Chukwuma", "Chinaza", "Chijiofor", "Chinweizu",
		"Chibuikem", "Chikamso", "Chikezie", "Chibueze", "Chukwumeka", "Chigozika", "Chikamara", "Chimaobim", "Chinonso", "Chinasa",
		"Chinelo", "Chukwuemeka", "Chukwuma", "Chizaram", "Chinwendu", "Chinedu", "Chigozie", "Chidiebere", "Chukwuebuka", "Chibundu",
		"Chinomnso", "Chibuihe", "Chukwuka", "Chukwunonso", "Chinonyelum", "Chibunna", "Chinaza", "Chukwudi", "Chibuzo", "Chijioke",
		"Chijindum", "Chinweike", "Chikamara", "Chikamso", "Chikezie", "Chimaobi", "Chimaobim", "Chinasa", "Chinelo", "Chinwendu",
		"Chinonso", "Chinomnso", "Chinonyelum", "Chukwubuka", "Chukwudi", "Chukwuebuka", "Chukwuka", "Chukwunonso", "Chukwunweike", "Chukwuma",
		"Chukwuweike", "Chukwutoo", "Chibuihe", "Chibundu", "Chibunna", "Chibuikem", "Chibuike", "Chibueze", "Chibueze", "Chibuike",
		"Chibuihe", "Chibundu", "Chibuikem", "Chibunna", "Chukwunonso", "Chukwutoo", "Chukwuma", "Chukwuweike", "Chukwuweike", "Chukwuemeka",
		"Chukwuka", "Chukwudi", "Chukwuebuka", "Chukwunonso", "Chukwunweike", "Chinedum", "Chinaza", "Chijindum", "Chinweike", "Chikamara",
		"Chikamso", "Chikezie", "Chikamso", "Chikezie", "Chibuike", "Chibueze", "Chibuzo", "Chijioke", "Chinwendu", "Chibundu",
		"Chukwunonso", "Chukwuweike", "Chukwudi", "Chukwuebuka", "Chibunna", "Chinemerem", "Chimaobi", "Chinonye", "Chukwunweike",
		"Chukwutoo", "Chukwuma", "Chinaza", "Chijiofor", "Chinweizu", "Chibuikem", "Chikamso", "Chikezie", "Chibueze", "Chukwumeka",
		"Chigozika", "Chikamara", "Chimaobim", "Chinonso", "Chinasa", "Chinelo", "Chukwuemeka", "Chukwuma", "Chizaram", "Chinwendu",
		"Chinedu", "Chigozie", "Chidiebere", "Chukwuebuka", "Chibundu", "Chinomnso", "Chibuihe", "Chukwuka", "Chukwunonso", "Chinonyelum",
		"Chibunna", "Chinaza", "Chukwudi", "Chibuzo", "Chijioke", "Chijindum", "Chinweike", "Chikamara", "Chikamso", "Chikezie",
		"Chimaobi", "Chimaobim", "Chinasa", "Chinelo", "Chinwendu", "Chinonso",
	}
	nigerianFemaleFirstNames = []string{
		"Chidinma", "Oluchi", "Adaeze", "Ngozi", "Oluwakemi", "Kehinde", "Chinyere", "Chiamaka", "Blessing", "Amara",
		"Nkechi", "Ifeoma", "Chisom", "Chidimma", "Nkem", "Chinelo", "Uchechi", "Obiageli", "Chioma", "Oluwabunmi",
		"Omolara", "Oluwaseun", "Funmilayo", "Omolola", "Titilayo", "Nneka", "Chinwe", "Folake", "Adebimpe", "Adetutu",
		"Titi", "Olajumoke", "Simisola", "Kikelomo", "Ireti", "Yetunde", "Oluwatosin", "Abimbola", "Ayo", "Tolulope",
		"Oluwafunmilayo", "Yemisi", "Ayomide", "Ibukun", "Morenike", "Olufunke", "Omolola", "Mojisola", "Folashade", "Toyin",
		"Bisola", "Ololade", "Olubunmi", "Bukola", "Ronke", "Kafayat", "Adenike", "Adetokunbo", "Anuoluwapo", "Yetunde",
		"Boluwatife", "Ronke", "Opeyemi", "Abisoye", "Bolaji", "Titi", "Kemi", "Bimbo", "Nifemi", "Opeyemi",
		"Kafilat", "Aminat", "Amina", "Munirat", "Bolanle", "Shade", "Eniola", "Lola", "Folakemi", "Bisoye",
		"Omotola", "Enitan", "Anike", "Ajoke", "Yewande", "Amope", "Abiodun", "Adeola", "Omowunmi", "Iyabo",
		"Adesuwa", "Adebola", "Dupe", "Ganiyat", "Alimat", "Khadijah", "Tawakalitu", "Halimah", "Mopelola", "Olubukunola",
		"Olubunmi", "Oluwadamilola", "Olufunmilola", "Oluwaseun", "Abisola", "Yetunde", "Kikelomo", "Bukunmi", "Bisoye", "Adenike",
		"Adetokunbo", "Toyin", "Ronke", "Kafayat", "Aminat", "Amina", "Bolanle", "Shade", "Bimbo", "Lola",
		"Folakemi", "Omolola", "Moji", "Folasade", "Ayo", "Bunmi", "Titi", "Kemi", "Bisi", "Simi",
		"Ibukun", "Morenike", "Olufunke", "Bukola", "Ronke", "Kafayat", "Adenike", "Adetokunbo", "Anuoluwapo", "Yetunde",
		"Boluwatife", "Ronke", "Opeyemi", "Abisoye", "Bolaji", "Titi", "Kemi", "Bimbo", "Nifemi", "Opeyemi",
		"Kafilat", "Aminat", "Amina", "Munirat", "Bolanle", "Shade", "Eniola", "Lola", "Folakemi", "Bisoye",
		"Omotola", "Enitan", "Anike", "Ajoke", "Yewande", "Amope", "Abiodun", "Adeola", "Omowunmi", "Iyabo",
		"Adesuwa", "Adebola", "Dupe", "Ganiyat", "Alimat", "Khadijah", "Tawakalitu", "Halimah", "Mopelola", "Olubukunola",
		"Olubunmi", "Oluwadamilola", "Olufunmilola", "Oluwaseun", "Abisola", "Yetunde", "Kikelomo", "Bukunmi", "Bisoye", "Adenike",
		"Adetokunbo", "Toyin", "Ronke", "Kafayat", "Aminat", "Amina", "Bolanle", "Shade", "Bimbo", "Lola",
		"Folakemi", "Omolola", "Moji", "Folasade", "Ayo", "Bunmi", "Titi", "Kemi", "Bisi", "Simi",
	}
	nigerianLastNames = []string{
		"Adeyemi", "Ogunleye", "Okafor", "Eze", "Nwachukwu", "Adewale", "Okeke", "Ogbonna", "Okafor", "Eze",
		"Ogundipe", "Onyemaechi", "Nwankwo", "Ogunnaike", "Ajayi", "Okoye", "Nwosu", "Adegoke", "Olajide", "Ogungbemi",
		"Adesina", "Olawale", "Ezeala", "Onyejekwe", "Adeleke", "Osagie", "Ezenwa", "Okonkwo", "Adeleye", "Olatunji",
		"Ezenwanyi", "Okorie", "Agwu", "Olumide", "Ezeji", "Okosun", "Agu", "Oluwaseun", "Ezeudu", "Okoye",
		"Aguirre", "Oluwole", "Fajemisin", "Okwuobi", "Akande", "Onwubiko", "Famuyiwa", "Okwute", "Akinlade", "Onwumere",
		"Folayan", "Olumhense", "Akintola", "Orji", "Gbadamosi", "Omobowale", "Akinyemi", "Osagiede", "Gberevbie", "Onyema",
		"Akintoye", "Oshin", "Gbolahan", "Osuntokun", "Akpan", "Osifo", "Gbemisola", "Osuntola", "Amaechi", "Osaghae",
		"Gbenga", "Oyeleke", "Amadi", "Osakwe", "Gbenga-Mustapha", "Oyeniyi", "Amaechina", "Osayande", "George", "Oyewole",
		"Amusan", "Osazuwa", "Gimba", "Raji", "Anene", "Osei", "Haastrup", "Rotimi", "Aniagolu", "Oshikoya",
		"Hamza", "Salako", "Anigbogu", "Osho", "Hammed", "Salami", "Anih", "Oshoala", "Haruna", "Salawu",
		"Anikwe", "Oshodi", "Hassan", "Samuel", "Anosike", "Osibote", "Ibe", "Sanni", "Asika", "Osifo",
		"Ibrahim", "Saraki", "Asobele", "Osinaike", "Idris", "Shittu", "Atolagbe", "Osita", "Ifeajika", "Shonubi",
		"Atolaiye", "Ositadinma", "Ifeanyi", "Siwoku", "Awoyale", "Osita-Njoku", "Ike", "Sobowale", "Ayodele", "Osuagwu",
		"Ikechi", "Sokoya", "Ayoola", "Osubor", "Ikemefuna", "Solade", "Azubuike", "Osuigwe", "Ikpeme", "Soleye",
		"Babalola", "Osuji", "Ikwuemesi", "Soremekun", "Babangida", "Osumba", "Iloabachie", "Sosina", "Bakare", "Osunde",
		"Imoukhuede", "Sowande", "Balogun", "Osungbade", "Isa", "Soyinka", "Bankole", "Osuntokun", "Isiaka", "Sule",
		"Barkindo", "Osuntola", "Iwueze", "Suleiman", "Bassey", "Osuolale", "Iyiola", "Sunmonu", "Bello", "Osuwade",
		"Jaja", "Suru", "Bello-Osagie", "Otobo", "Jacob", "Taiwo", "Birabi", "Owa", "Jega", "Tamuno",
		"Bolaji", "Owolabi", "Jimoh", "Tanimowo", "Braimah", "Oyakhilome", "Jumare", "Tanimu", "Buhari", "Oyegun",
		"Kadiri", "Tari", "Coker", "Oyenekan", "Kalango", "Tella", "Dabiri", "Oyesanmi", "Kalu", "Tijani",
		"Dahunsi", "Oyewumi", "Katsina", "Tinubu", "Dakolo", "Oyinlola", "Kazeem", "Tomori", "Dambazzau", "Oyinloye",
		"Kingsley", "Tonye", "Dangote", "Oyinloye", "Kolawole", "Toyo", "Danjuma", "Oyinsan", "Kumuyi", "Udechukwu",
		"Dantata", "Oyinsan", "Ladele", "Udoh", "Daramola", "Oyofo", "Ladoja", "Udoji", "Dauda", "Oyekan",
		"Lawal", "Udomboso", "Davies", "Oyelade", "Lemu", "Udom", "Debule", "Oyeniran", "Lere", "Ukaegbu",
		"Dekibo", "Oyewole", "Liadi", "Uko", "Dickson", "Oyewole", "Lola", "Ukpe", "Dokubo", "Oyinlola",
	}
)
