package namegen

var (
	spanishMaleFirstNames = []string{
		"Aaron", "Adolfo", "Adrián", "Agustín", "Aitor", "Albert", "Alberto", "Alejandro", "Álex", "Alexander", "Alfonso", "Alfredo", "Álvaro", "Andrés", "Ángel", "Antonio", "Arturo",
		"Bartolomé", "Borja",
		"Carlos", "César", "Christian", "Cristian", "Cristóbal",
		"Daniel", "Darío", "David", "Diego", "Domingo",
		"Eduardo", "Emilio", "Enrique", "Ernesto", "Esteban", "Eugenio",
		"Felipe", "Félix", "Fernando", "Francisco", "Francisco Javier", "Francisco José",
		"Gabriel", "Germán", "Gonzalo", "Gregorio", "Guillermo",
		"Héctor", "Hipólito", "Hugo",
		"Ignacio", "Íker", "Isaac", "Ismael", "Iván",
		"Jaime", "Javier", "Jesús", "Joan", "Joaquín", "Joel", "Jonathan", "Jordi", "Jorge", "José", "José Ángel", "José Antonio", "José Carlos", "Jose Francisco", "José Ignacio", "José Luis", "José Manuel", "José María", "José Miguel", "José Ramón", "Josep", "Juan", "Juan Antonio", "Juan Carlos", "Juan Francisco", "Juan José", "Juan Luis", "Juan Manuel", "Julián", "Julio",
		"Lorenzo", "Lucas", "Luis", "Luis Miguel",
		"Manuel", "Marc", "Marco", "Marcos", "Mariano", "Mario", "Martín", "Mateo", "Miguel", "Miguel Ángel", "Mohamed",
		"Nicolás", "Norberto",
		"Octavio", "Óscar",
		"Pablo", "Pau", "Pedro",
		"Quinto", "Quintiliano", "Quique",
		"Rafael", "Ramón", "Raúl", "Ricardo", "Roberto", "Rodrigo", "Rubén",
		"Salvador", "Samuel", "Santiago", "Sebastián", "Sergio",
		"Timoteo", "Tomás",
		"Umberto", "Unai",
		"Valentín", "Vicente", "Víctor", "Víctor Manuel",
		"Wenceslao",
		"Xavier",
		"Yago",
		"Zacarías",
	}

	spanishFemaleFirstNames = []string{
		"Adriana", "Ainhoa", "Alba", "Alejandra", "Alicia", "Amparo", "Ana", "Ana Belén", "Ana Isabel", "Ana María", "Andrea", "Ángela", "Ángeles", "Anna", "Antonia", "Asunción", "Aurora",
		"Beatriz", "Begoña", "Belén", "Blanca",
		"Carla", "Carmen", "Carolina", "Catalina", "Celia", "Clara", "Claudia", "Concepción", "Consuelo", "Cristina",
		"Daniela", "Dolores",
		"Elena", "Elisa", "Emilia", "Emma", "Encarnación", "Esperanza", "Esther", "Eugenia", "Eva", "Eva María",
		"Fátima", "Francisca",
		"Gabriela", "Gema", "Gloria",
		"Helena", "Hilaria", "Hipólita",
		"Inés", "Inmaculada", "Irene", "Isabel",
		"Josefa", "Josefina", "Juana", "Julia",
		"Laura", "Lidia", "Lorena", "Lourdes", "Lucía", "Luisa", "Luz",
		"Magdalena", "Manuela", "Mar", "Margarita", "María", "María Ángeles", "María Antonia", "María del Carmen", "María Concepción", "María Dolores", "María Elena", "María Isabel", "María Jesús", "María José", "María Josefa", "María Luisa", "María del Mar", "María Mercedes", "María Nieves", "María Pilar", "María Rosa", "María Rosario", "María Soledad", "María Teresa", "María Victoria", "Marina", "Marta", "Martina", "Mercedes", "Milagros", "Miriam", "Mónica", "Montserrat",
		"Natalia", "Nerea", "Nieves", "Noelia", "Nuria",
		"Olga", "Olvido",
		"Patricia", "Paula", "Pilar", "Purificación",
		"Quirina",
		"Raquel", "Remedios", "Rocío", "Rosa", "Rosa María", "Rosario",
		"Sandra", "Sara", "Silvia", "Sofía", "Soledad", "Sonia", "Susana",
		"Tatiana", "Teresa",
		"Úrsula",
		"Vanesa", "Verónica", "Victoria", "Virginia",
		"Wendy",
		"Yolanda",
		"Zenobia",
	}

	spanishLastNames = []string{
		"Abad", "Ábalos", "Abar", "Abascal", "Abeita", "Abeyta", "Abila", "Abrantes", "Abrego", "Abrigo", "Abril", "Acebo", "Acedo", "Acero", "Acevedo", "Aceves", "Adames", "Adán", "Adriano", "África", "Aguado", "Aguas", "Aguayo", "Agüero", "Águila", "Aguilar", "Aguilar", "Aguilera", "Aguiniga", "Agustín", "Ahumada", "Aja", "Alameda", "Alamillo", "Álamo", "Alanis", "Alaniz", "Alarcón", "Alatorre", "Alba", "Albarado", "Albarrán", "Alberto", "Albo", "Albuquerque", "Alcalá", "Alcalde", "Alcantar", "Alcántara", "Alcaraz", "Alcázar", "Alcócer", "Alcón", "Alcóser", "Alderete", "Aldrete", "Alegre", "Alegría", "Alejandre", "Alejandro", "Alejo", "Alejos", "Alemán", "Alfaro", "Alfonso", "Algarín", "Alire", "Allende", "Alma", "Almanza", "Almanzar", "Almaraz", "Almas", "Almazán", "Almendárez", "Almodóvar", "Almonte", "Alo", "Alonso", "Alonzo", "Alpizar", "Altamirano", "Alvarado", "Álvarez", "Álvaro", "Alvear", "Alvérez", "Alviar", "Alvidrez", "Alvillar", "Alviso", "Alvizo", "Amado", "Amador", "Amaya", "Amescua", "Amezquita", "Amo", "Amor", "Arias",
		"Benitez", "Bielsa", "Blanco", "Blasco", "Blásquez", "Bravo", "Bueno",
		"Caballero", "Cabrera", "Calvo", "Campos", "Cano", "Carmona", "Carrasco", "Castillo", "Castro", "Cortes", "Crespo", "Cruz",
		"Delgado", "Díaz", "Díez", "Domínguez", "Durán",
		"Echevarría", "Echeverría", "Esteban", "Etxeberria",
		"Fernández", "Ferrer", "Flores", "Fraile", "Fuentes",
		"Gallardo", "Gallego", "Gámez", "García", "Garrido", "Gil", "Giménez", "Gómez", "González", "Guerrero", "Gutiérrez",
		"Hernández", "Herrera", "Herrero", "Hidalgo",
		"Ibáñez", "Iglesias", "Irureta", "Iruretagoyena",
		"Jiménez", "Jémez",
		"Kaiser",
		"León", "López", "Lorenzo", "Lozano",
		"Marín", "Márquez", "Martín", "Martínez", "Medina", "Méndez", "Molina", "Montero", "Montoro", "Mora", "Morales", "Moreno", "Moya", "Muñoz",
		"Navarro", "Nieto", "Núñez",
		"Ortega", "Ortiz",
		"Parra", "Pascual", "Pastor", "Peña", "Pérez", "Prieto",
		"Quiñones", "Quiñónez",
		"Ramírez", "Ramos", "Reyes", "Rodríguez", "Rojas", "Román", "Romero", "Rubio", "Ruíz",
		"Sáez", "Sánchez", "Santana", "Santiago", "Santos", "Sanz", "Serrano", "Soler", "Soto", "Suárez",
		"Torres", "Trinidad",
		"Ugarte", "Ulloa", "Urbizu", "Uribe",
		"Vargas", "Vázquez", "Vega", "Velasco", "Vicente", "Vidal",
		"Xerez", "Ximénez",
		"Yánez", "Yepes", "Yuste",
		"Zabala", "Zambrano", "Zamora", "Zamorano"}
)
