package namegen

var (

	spanishFirstNames = []string{"maría", "carmen", "antonio", "lucía", "hugo", "isabel", "pilar", "manuel", "juan", "javier","Sofia","Isabella","Camila","Valentina","Valeria","Mariana","Luciana","Daniela","Gabriela","Victoria","Martina","Lucia","Ximena/Jimena","Sara","Samantha","Maria","José","Emma","Catalina","Julieta","Mía","Antonella","Renata","Emilia","Natalia","Zoe","Nicole","Paula","Amanda","María","Fernanda","Emily","Antonia","Alejandra","Juana","Andrea","Manuela","Ana","Sofia","Guadalupe","Agustina","Elena","María","Bianca","Ariana","Ivanna","Abril","Florencia","Carolina","Maite","Rafaela","Regina","Adriana","Michelle","Alma","Violeta","Salomé","Abigail","Juliana","Valery","Isabel","Montserrat","Allison","Jazmín","Julia","Lola","Luna","Ana","Delfina","Alessandra","Ashley","Olivia","Constanza","Paulina","Rebeca","Carla","María","Paula","Micaela","Fabiana","Miranda","Josefina","Laura","Alexa","María","Alejandra","Luana","Fátima","Sara","Sofía","Isidora","Malena","Romina","Ana","Paula","Mariangel","Amelia","Elizabeth","Aitana","Ariadna","María","Camila","Irene","Silvana","Clara","Magdalena","Sophie","Josefa","Boys'","Names","Santiago","Sebastián","Matías","Mateo","Nicolás","Alejandro","Diego","Samuel","Benjamín","Daniel","Joaquín","Lucas","Tomas","Gabriel","Martín","David","Emiliano","Jerónimo","Emmanuel","Agustín","Juan","Pablo","Juan","José","Andrés","Thiago","Leonardo","Felipe","Ángel","Maximiliano","Christopher","Juan","Diego","Adrián","Pablo","Miguel","Ángel","Rodrigo","Alexander","Ignacio","Emilio","Dylan","Bruno","Carlos","Vicente","Valentino","Santino","Julián","Juan","Sebastián","Aarón","Lautaro","Axel","Fernando","Ian","Christian","Javier","Manuel","Luciano","Francisco","Juan","David","Iker","Facundo","Rafael","Alex","Franco","Antonio","Luis","Isaac","Máximo","Pedro","Ricardo","Sergio","Eduardo","Bautista","Miguel","Cristóbal","Kevin","Jorge","Alonso","Anthony","Simón","Juan","Joshua","Diego","Alejandro","Juan","Manuel","Mario","Alan","Josué","Gael","Hugo","Matthew","Ivan","Damián","Lorenzo","Juan","Martín","Esteban","Álvaro","Valentín","Dante","Jacobo","Jesús","Camilo","Juan","Esteban","Elías"}
	spanishLastNames = []string{"garcía", "gonzález", "fernández", "rodríguez", "lópez", "martínez", "sánchez", "pérez", "gómez", "martín","Abad","Abalos","Abar","Abascal","Abeita","Abeyta","Abila","Abrantes","Abrego","Abrigo","Abril","Acebo","Acedo","Acero","Acevedo","Aceves","Adames","Adan","Adriano","Africa","Aguado","Aguas","Aguayo","Aguero","Aguila","Aguilar","Aguilera","Aguiniga","Agustin","Ahumada","Aja","Alameda","Alamillo","Alamo","Alanis","Alaniz","Alarcon","Alatorre","Alba","Albarado","Albarran","Alberto","Albo","Albuquerque","Alcala","Alcalde","Alcantar","Alcantara","Alcaraz","Alcazar","Alcocer","Alcon","Alcoser","Alderete","Aldrete","Alegre","Alegria","Alejandre","Alejandro","Alejo","Alejos","Aleman","Aleman","Alfaro","Alfonso","Algarin","Alire","Allende","Alma","Almanza","Almanzar","Almaraz","Almas","Almazan","Almendarez","Almodovar","Almonte","Alo","Alonso","Alonzo","Alpizar","Altamirano","Alvarado","Alvarez","Alvaro","Alvear","Alverez","Alviar","Alvidrez","Alvillar","Alviso","Alvizo","Amado","Amador","Amaya","Amescua","Amezquita","Amo","Amor","Amor"}


)

